services:
    app:
      container_name: frontend_app
      image: frontend_app
      env_file:
          - .env
      build:
          dockerfile: Dockerfile
          context: .
      ports:
          - 3000:3000
      volumes:
          - ./:/app
